"""Action trace recorder + stable-script emitter.

Every tool call appends an entry. generate_stable_script_from_trace()
emits a self-contained Python script that uses ONLY automation_id /
name / control_type — never coords. If a step originally used coord/OCR
fallback, it is emitted with a TODO marker so the user can substitute.
"""

from __future__ import annotations

import json
import logging
import threading
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path

log = logging.getLogger("windows_gui_mcp.trace")


@dataclass
class TraceEntry:
    ts: float
    tool: str
    args: dict
    result: dict
    ok: bool
    note: str = ""


@dataclass
class Trace:
    started_at: float = field(default_factory=time.time)
    entries: list[TraceEntry] = field(default_factory=list)


_lock = threading.Lock()
_current: Trace = Trace()
_TRACE_DIR = Path.home() / ".windows_gui_mcp" / "traces"


def reset() -> None:
    global _current
    with _lock:
        _current = Trace()


def record(tool: str, args: dict, result: dict, ok: bool, note: str = "") -> None:
    safe_args = _sanitize(args)
    safe_result = _sanitize(result)
    with _lock:
        _current.entries.append(
            TraceEntry(ts=time.time(), tool=tool, args=safe_args, result=safe_result, ok=ok, note=note)
        )


def snapshot() -> dict:
    with _lock:
        return {
            "started_at": _current.started_at,
            "entries": [asdict(e) for e in _current.entries],
        }


def save(path: str | None = None) -> str:
    _TRACE_DIR.mkdir(parents=True, exist_ok=True)
    p = Path(path) if path else _TRACE_DIR / f"trace_{int(time.time())}.json"
    p.write_text(json.dumps(snapshot(), indent=2, ensure_ascii=False))
    return str(p)


def _sanitize(d: dict) -> dict:
    """Drop binary blobs (base64 screenshots) from the persisted trace."""
    out: dict = {}
    for k, v in d.items():
        if isinstance(v, str) and len(v) > 1024 and k.lower() in {"base64", "image", "img"}:
            out[k] = f"<{len(v)} bytes elided>"
        elif isinstance(v, dict):
            out[k] = _sanitize(v)
        else:
            out[k] = v
    return out


def generate_stable_script_from_trace(out_path: str | None = None) -> dict:
    """Emit a Python script using pywinauto that replays the trace.

    Steps that used image/OCR/coord fallback are emitted as TODO
    placeholders so the user can substitute a stable identifier.
    """
    snap = snapshot()
    lines: list[str] = [
        "# auto-generated by windows-gui-mcp — replays a recorded UI trace",
        "# RULE: never reintroduce coordinate clicks; replace TODO markers.",
        "from pywinauto import Desktop",
        "import time",
        "",
        "desktop = Desktop(backend='uia')",
        "",
    ]
    todo_count = 0
    for e in snap["entries"]:
        if not e["ok"]:
            lines.append(f"# SKIPPED (was failing): {e['tool']} {e['args']}")
            continue
        tool, args = e["tool"], e["args"]
        if tool == "focus_window":
            tre = args.get("title_regex", "")
            lines.append(f"win = desktop.window(title_re={tre!r})")
            lines.append("win.set_focus()")
        elif tool == "click_element":
            spec = args.get("spec") or {}
            kw = _spec_to_kw(spec)
            if kw:
                lines.append(f"win.descendants({kw})[{spec.get('nth', 0)}].click_input()")
            else:
                todo_count += 1
                lines.append(f"# TODO[{todo_count}]: replace coord/image click with stable id — {args}")
        elif tool == "type_text":
            spec = args.get("spec") or {}
            text = args.get("text", "")
            kw = _spec_to_kw(spec)
            if kw:
                lines.append(f"el = win.descendants({kw})[{spec.get('nth', 0)}]")
                lines.append("el.set_focus()")
                lines.append(f"el.type_keys({text!r}, with_spaces=True, set_foreground=False)")
            else:
                lines.append(f"win.type_keys({text!r}, with_spaces=True, set_foreground=False)")
        elif tool == "hotkey":
            lines.append(f"win.type_keys({args.get('keys', '')!r}, set_foreground=False)")
        elif tool == "wait_until_element":
            spec = args.get("spec") or {}
            kw = _spec_to_kw(spec)
            timeout = args.get("timeout", 5)
            if kw:
                lines.append(f"win.descendants({kw})[0].wait('visible', timeout={timeout})")
        else:
            lines.append(f"# {tool}({args}) — informational, no replay needed")
        lines.append("time.sleep(0.2)")
    body = "\n".join(lines) + "\n"
    _TRACE_DIR.mkdir(parents=True, exist_ok=True)
    p = Path(out_path) if out_path else _TRACE_DIR / f"replay_{int(time.time())}.py"
    p.write_text(body)
    return {"path": str(p), "lines": len(lines), "todo_markers": todo_count}


def _spec_to_kw(spec: dict) -> str:
    bits = []
    if spec.get("automation_id"):
        bits.append(f"auto_id={spec['automation_id']!r}")
    if spec.get("name"):
        bits.append(f"title={spec['name']!r}")
    if spec.get("control_type"):
        bits.append(f"control_type={spec['control_type']!r}")
    if spec.get("class_name"):
        bits.append(f"class_name={spec['class_name']!r}")
    return ", ".join(bits)
